### ISSUE TITLE
Добавить авторизацию

### ISSUE THREAD

**Issue by niqitosiq** [volsu-infosystem/service-schedule#10]
Создать механизм авторизации по электронному адресу. Сначала запрос на отправку кода на эл.почту, потом его проверка. Если верно, вернуть токен доступа клиенту.
### Требования
* Ограничить время жизни кода до 10 минут (после он становится недействительным)
* Код состоит из 5 цифр
* Механизм авторизации должен поддерживать не менее 10 авторизаций в минуту
* Авторизация только для почтовых адресов на домене @volsu.ru

**Дедлайн  14.11.2020**

**Comment by DVegasa** [comment]
Сделано
