### ISSUE TITLE
Запилить админку

### ISSUE THREAD

**Issue by niqitosiq** [volsu-infosystem/service-schedule#11]
UI для эндпоинтов администрирования.

Базовые операции (добавление, обновление, удаление).

**Comment by DVegasa** [comment]
@niqitosiq , если работы тут не было, давай закроем задачу и создадим новую с более точным описанием?

**Comment by niqitosiq** [comment]
> @niqitosiq , если работы тут не было, давай закроем задачу и создадим новую с более точным описанием?

Можно
