### ISSUE TITLE
Сидер для парсинга программ обучения групп

### ISSUE THREAD

**Issue by niqitosiq** [volsu-infosystem/service-schedule#35]
- Получение списка Учебных планов с сайта  https://volsu.ru/activities/education/eduprogs/ooplist.php?id=03
- Парсинг названий програм ( УП это то, что видно, если провалистя в обр. программу)
![изображение](https://user-images.githubusercontent.com/15576320/109519473-52693900-7abc-11eb-8dcf-5aefe78bd6fc.png)
- Создание программы с помощью запроса к нашему бекенду
- Парсинг учебных планов
![изображение](https://user-images.githubusercontent.com/15576320/109519533-614feb80-7abc-11eb-8bc6-693f669bd74c.png)
- Создание сущности учебных единиц и связывание его с учебным планом, созданным раньше
Делать это можно с помощью любого языка и технологии. Думаю, лучший вариант это питон https://pdfreader.readthedocs.io/en/latest/

Либо, может получится узнать у деканата как получить эти данные в более приемлемом виде @DVegasa

**Comment by DVegasa** [comment]
Пока пауза по этому таску, делать сейчас не нужно. В течении пары дней скажу что с этим и чё делать дальше
